name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
<<<<<<< HEAD
        run: npx jsr publish
=======
        run: npx jsr publish
>>>>>>> cc1db55 (publish)
